global_costmap:
  global_frame:               /odom
  rolling_window:             true
  track_unknown_space:        true
  width:                      10.0
  height:                     10.0
  origin_x:                   -5.0
  origin_y:                   -5.0
  
  plugins:
    - {name: obstacles_costmap2d,       type: "costmap_2d::ObstacleLayer"}
    - {name: inflation,                 type: "costmap_2d::InflationLayer"}
  




