global_costmap:
    global_frame: map
    rolling_window: false
    track_unknown_space: false
    width:                      100.0
    height:                     100.0
    #origin_x:                   -50.0
    #origin_y:                   -50.0

    plugins:
    - {name: static,                  type: "costmap_2d::StaticLayer"}
    - {name: inflation,               type: "costmap_2d::InflationLayer"}
